//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        public int ID_Fournisseur { get; set; }
        public string Nom_Fournisseur { get; set; }
        public string Adresse_Fournisseur { get; set; }
        public string Téléphone_Fournisseur { get; set; }
    }
}
