//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appGestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int ID_Produit { get; set; }
        public string Nom_Produit { get; set; }
        public string Reference_Produit { get; set; }
        public string Quantite_Produit { get; set; }
        public string Rayon_Produit { get; set; }
        public string Designation_Produit { get; set; }
    }
}
